import { Nunito_Sans, Raleway, Ropa_Sans } from '@next/font/google'
import Head from 'next/head'
import Link from 'next/link'
import styles from './Layout.module.css'

type Props = {
  logo: React.ReactNode
  children: React.ReactNode
}

const raleway = Raleway({
  variable: '--raleway-font',
  subsets: ['latin'],
})

const nunito = Nunito_Sans({
  weight: '400',
  variable: '--nunito-font',
  subsets: ['latin'],
})

const ropa = Ropa_Sans({
  weight: '400',
  variable: '--ropa-font',
  subsets: ['latin'],
})

export default function Layout({ logo, children }: Props) {
  return (
    <div
      className={`${styles.root} ${nunito.variable} ${raleway.variable} ${ropa.variable}`}
    >
      <Head>
        <title>Iron Man Landing Page</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <div className={styles.logo}>{logo}</div>
        <nav className={styles.nav}>
          <Link className="link" href="#sign-in">
            Sign In
          </Link>
          <Link className="button" href="#sign-up">
            Sign Up
          </Link>
        </nav>
      </div>
      <main>{children}</main>
    </div>
  )
}
